# Generated by Django 3.2.6 on 2021-08-17 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=50)),
                ('canal', models.CharField(max_length=20)),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nometeam', models.CharField(max_length=40)),
                ('Desc', models.CharField(max_length=15)),
                ('Logo', models.ImageField(blank=True, upload_to='foto/%y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricaoPartida', models.CharField(max_length=50)),
                ('data', models.DateTimeField()),
                ('mostrar', models.BooleanField(default=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.canais')),
                ('nometeam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.teammates')),
            ],
        ),
    ]
